### ISSUE TITLE
Supress opening the file dialogue box

### ISSUE THREAD

**Issue by rdearman** [ssb22/gradint#2]
More of a request than an issue. 

When you create an MP3 or other audio, the gradint pops up a file dialogue with the new file in it. It would be nice if there were some kind of checkbox to suppress this behaviour? If you're making multiple lessons into MP3 it would be good to stop this behaviour.

**Comment by ssb22** [comment]
Hi Rick, the easiest way to make multiple lessons in a batch is to use the command line.  The graphical window is to help people do simple things without needing the command line, so I don't want to put **too** many advanced options on it (I'm told it's confusing enough already); sufficiently advanced users can do what they want on the command line, such as:

    for N in 1 2 3 4 5 6 7 8 9; do python gradint.py "outputFile='lesson$N.mp3'"; done

The instructions for all of this are in `advanced.txt` although I agree they could do with being written a bit more clearly in places ☺

**Comment by rdearman** [comment]
Great! I did read the text file, but didn't remember seeing that bit. Probably because I was focusing on something else. One additional query. If I have already generated 10 output files, and use:
```
 for i in {10..50}
```
it will output 11, 12, ...

I'm sure this is the case, but better safe than sorry.

**Comment by ssb22** [comment]
Yes, if your shell is `bash` you can do:

    for i in {10..50}; do python gradint.py "outputFile='lesson$i.mp3'"; done

I just didn't write it that way last time on the off-chance that you (or someone else reading this) might be running an old version of `sh` that doesn't support the `{X..Y}` syntax
