### ISSUE TITLE
Popping sound in lessons

### ISSUE THREAD

**Issue by rdearman** [ssb22/gradint#4]
When I generate a lesson.mp3 I get a "popping" sound in the output file.
![popping](https://user-images.githubusercontent.com/4869065/168569688-3212f992-d510-481c-97f9-00b09f27f3e8.png)
I'm sure you addressed this problem before, and it was something to do with the encoder being used. I pulled the latest copy from github and built it, but still have the same issue. I have the following installed:

sox:      SoX v14.4.2
madplay 0.15.2 (beta)
mpg123 1.25.13
LAME 64bits version 3.100 

I think I found the part where you'd fixed this before?

> Ah, I managed to root-cause the static problem.
>
> Gradint uses LAME to create MP3 files. Unfortunately, the parameters it needs to send to LAME vary depending on which version of LAME is installed on the system. Therefore, Gradint checks the LAME version number, and does one thing if it gets 3.97 or below, but another thing if it gets 3.98 or above.
> 
> Unfortunately, the code to do this read only the first 4 characters of the version number, so when LAME hit version 3.100, Gradint started to read this as 3.10, and incorrectly applied the "before 3.97" parameters, causing LAME to read the bytes of our samples in the wrong order, turning anything other than silence into static (but only when creating MP3 files, not when creating OGG or WAV or SPX).
> 
> I didn't notice this during testing because I had not tried version 3.100 of LAME.

**Comment by ssb22** [comment]
Hi Rick, I think we're looking at a different issue this time because your Audacity screenshot is showing not all of the words are 'popping', just some of them.  (The previous issue with LAME parameters would be affecting all of them.)

We need to figure out what's different about the words that 'pop', is there any chance you could email me your files so I can take a look sometime?

Thanks.

Silas

**Comment by rdearman** [comment]
Just to update anyone else who might have this problem. It was because the program puts in beeps to let the listener know it is still active, but if you just want silence then in the advanced setting "beepThreshold" set this stupidly high like 99999 to remove the beeps.
