### ISSUE TITLE
TTS voices on Windows 10 don't change

### ISSUE THREAD

**Issue by RickCarlino** [ssb22/gradint#5]
**UPDATE:** The solution to the problem is [here](https://github.com/ssb22/gradint/issues/5#issuecomment-1370247748). The root cause was a spelling mistake in the voice name. You can list all available voices to check spelling by running `ptts.exe -vl`.

---

Greetings!

I am re-visiting Gradint after being away from language studies for many years. I am glad to see you are still maintaining the project.

I have installed the latest build from the Gradint website.

I cannot hear Korean text-to-speech, nor can I change the default voice for English (I attempted to use "Microsoft Zira Desktop" but it does not use that voice).

I have verified that I have the voices installed by listing installed voices via HTML5. That is to say, Firefox was able to detect the TTS voices.

My `advanced.txt` file is as follows:

```
otherLanguages = []
possible_otherLanguages = []
otherFirstLanguages = []
prefer_espeak = ""
sapiVoices = {
    "en" : ("Microsoft Zira Desktop", 8000),
    "ko" : ("Microsoft Heami Desktop", 8000)
}

sapiSpeeds = {
# "en": -5, "zh": +3   (but without the # at the beginning)
}
```

I have redacted the latter half of the file since it is very large. Please let me know if you need more information and thanks again for maintaining the project!

**Comment by ssb22** [comment]
Thanks Rick.  That's odd.  Can you confirm that there's a `ptts.exe` in the Gradint folder?  What happens if you shift-rightclick on the Gradint folder to get a command prompt there, and put

    ptts -vl

to get the list of voices recognised by ptts?

**Comment by RickCarlino** [comment]
Thanks for the quick response @ssb22 .

Here's the output of `ptty.exe -vl`:

```
Microsoft David Desktop - English (United States)
Microsoft Zira Desktop - English (United States)
Microsoft Heami Desktop - Korean
```

Is there any way I could run Gradint in "verbose mode" to possibly capture silent errors or warnings?

**Comment by RickCarlino** [comment]
@ssb22 OK, I see what happened. It was a typo on my part. I was mirroring the format of the SAPI voice name in `advanced.txt` when I should have been using the literal name of the voice (I omitted the hyphen and language name after the voice name). A working version of my `advanced.txt` file is pasted below for anyone who makes the same mistake:

```
sapiVoices = {
    "en" : ("Microsoft Zira Desktop - English (United States)", 16000),
    "ko" : ("Microsoft Heami Desktop - Korean", 16000)
}
```
